blank_issues_enabled: true
contact_links:
  - name: Kontaktovat autora
    url: https://www.facebook.com/martin.tomanek.3150
    about: Chci kontaktovat autora kvůli něčemu jinému (Facebook).
  - name: Veřejně si postěžovat
    url: https://www.facebook.com/groups/137034543034563
    about: Chci si postěžovat v Letenské partě (Facebook).
