name: 游늯 Nahl치sit nespr치vnou informaci na str치nce
title: "Nespr치vn치 informace: "
description: Na str치nce je nespr치vn치 informace (nap콏. na kol칤k치ch se d치 bobovat, na rybn칤캜ku se d치 bruslit)
labels:
  - informace
body:
  - type: input
    attributes:
      label: Str치nka
      description: Odkaz na str치nku, kde je nespr치vn치 informace.
      placeholder: https://www.nevitejestli.cz/se-da-bobovat-na-kolikach/
    validations:
      required: true
  - type: textarea
    attributes:
      label: Popis
      description: Popi코te, co je na str치nce nespr치vn캩.
      placeholder: Na kol칤k치ch se ned치 bobovat.
    validations:
      required: true
